name: CI - RealtimeLeaderBoard

on:
  push:               # chạy khi có commit push
    branches:
      - '**'          # mọi nhánh
  pull_request:       # chạy khi có pull request
    branches:
      - '**'          # mọi nhánh

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Run Unit Tests
        run: mvn test

      - name: Run Checkstyle
        run: mvn checkstyle:check || true

      - name: Run SpotBugs
        run: mvn com.github.spotbugs:spotbugs-maven-plugin:check || true

      - name: Run CPD (duplicate code check)
        run: mvn pmd:cpd-check || true

#      - name: SonarQube Scan
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        run: |
#          mvn sonar:sonar \
#            -Dsonar.projectKey=my-springboot-project \
#            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
#            -Dsonar.login=${{ secrets.SONAR_TOKEN }}